// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5iHafkC7Jfxm-q1qnr5BXZxdCZxALxp0',
    appId: '1:197207258569:web:c12233d3755847cadc6418',
    messagingSenderId: '197207258569',
    projectId: 'offline-service-booking',
    authDomain: 'offline-service-booking.firebaseapp.com',
    storageBucket: 'offline-service-booking.firebasestorage.app',
    measurementId: 'G-YDR26TRE03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Mesl_LbDrs6s44Vku8vDY50r-kZ4pr4',
    appId: '1:197207258569:android:b0300ae143c254b6dc6418',
    messagingSenderId: '197207258569',
    projectId: 'offline-service-booking',
    storageBucket: 'offline-service-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rA4Q-ykWHmuFpA3_et7v1lbOG6fxb50',
    appId: '1:197207258569:ios:b1d75bfe2d69c866dc6418',
    messagingSenderId: '197207258569',
    projectId: 'offline-service-booking',
    storageBucket: 'offline-service-booking.firebasestorage.app',
    iosBundleId: 'com.example.offlineServiceBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2rA4Q-ykWHmuFpA3_et7v1lbOG6fxb50',
    appId: '1:197207258569:ios:b1d75bfe2d69c866dc6418',
    messagingSenderId: '197207258569',
    projectId: 'offline-service-booking',
    storageBucket: 'offline-service-booking.firebasestorage.app',
    iosBundleId: 'com.example.offlineServiceBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5iHafkC7Jfxm-q1qnr5BXZxdCZxALxp0',
    appId: '1:197207258569:web:5c3c23b2c52aa77ddc6418',
    messagingSenderId: '197207258569',
    projectId: 'offline-service-booking',
    authDomain: 'offline-service-booking.firebaseapp.com',
    storageBucket: 'offline-service-booking.firebasestorage.app',
    measurementId: 'G-139WS54PT6',
  );
}
